#!/usr/bin/env python
"""Reconcilia duas listas de categorias produzidas em execuções independentes da Etapa 2
(scripts/generate_consenso_categories.py) sobre bases de justificativa diferentes (v1 e v2,
mesma amostra de consenso, mesmo método, textos de justificativa reescritos pelo Gemini em
cada rodada -- variância normal de regeneração de LLM, não dados substancialmente diferentes:
ver comparação manual que motivou este script).

Em vez de escolher arbitrariamente uma das duas listas, pede-se a um LLM que funda as
categorias equivalentes entre as duas rodadas e preserve as que são distintas e não
redundantes em qualquer uma delas -- uma única chamada, mesmo padrão de Etapa 2 (DeepSeek, sem
teto de tokens/minuto relevante aqui dado o payload pequeno).

Uso:
  uv run python -m scripts.reconcile_consenso_categories
  uv run python -m scripts.reconcile_consenso_categories --v1 data/analysis/consenso_categorias.json --v2 data/analysis/consenso_categorias_v2.json --output data/analysis/consenso_categorias_reconciliadas.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from mcp_pipeline.config import DATA_DIR
from mcp_pipeline.evaluation.judges.base import JudgeBalanceExhausted, JudgeError, JudgeRefusal
from mcp_pipeline.logging_setup import setup_logging
from scripts.generate_consenso_categories import (
    Category,
    _DEEPSEEK_TIMEOUT_SECONDS,
    _DEEPSEEK_BASE_URL,
)

import os
import requests

logger = setup_logging("reconcile_consenso_categories")

DEFAULT_MODEL = "deepseek-flash"

SYSTEM_INSTRUCTION = """You are a qualitative research assistant reconciling two independently-produced sets of thematic categories for an undergraduate thesis ("Model Context Protocol (MCP): Avaliação da Qualidade de Descrições de Tools com Base em Contexto de Código-Fonte"). Both sets came from the SAME inductive thematic analysis method (Braun & Clarke, 2006), applied to the SAME underlying sample of tools, in two separate runs -- the justification texts fed into each run were independently regenerated by an LLM (same underlying facts, different wording each time), so the two category sets differ partly due to real differences in emphasis and partly due to ordinary run-to-run variance in a single-pass inductive coding process. Each category in each set is a Title Case name (2-5 words) plus a 2-3 sentence description of a MECHANISM (what kind of thing the source code reveals that the tool's natural-language description did not), never a rubric component and never a direction of score change.

You will receive a JSON object with two keys, "set_a" and "set_b", each a JSON array of {"category": ..., "description": ...} objects.

Task: produce ONE final, reconciled list of categories that:
1. Merges categories from the two sets that describe the same underlying mechanism, even when worded differently or at different granularity, into a single category with the clearer name and a description that captures the union of what both originals described.
2. Preserves categories that appear, with no real equivalent, in only ONE of the two sets, as long as they describe a genuinely distinct, recurring mechanism -- do not drop a category just because it is unique to one set.
3. When one set splits a mechanism into two categories while the other set merges it into one, make a deliberate choice about the right granularity for distinguishing analytically different documentation gaps, and resolve it explicitly (either keep them split, with sharper non-overlapping descriptions, or merge them, with a description broad enough to cover both).
4. Avoids redundancy: no two categories in the final list should classify the same justification the same way almost every time.

Output ONLY a JSON object with exactly one key, "categories", whose value is a JSON array of {"category": "<Title Case name>", "description": "<2-3 sentence description>"} objects, 10 to 16 entries. No text before or after it. Write everything in English."""


def _call_deepseek_reconcile(set_a: list[dict], set_b: list[dict], model: str, api_key: str) -> list[Category]:
    url = f"{_DEEPSEEK_BASE_URL}/chat/completions"
    headers = {"Content-Type": "application/json", "Authorization": f"Bearer {api_key}"}
    payload = {"set_a": set_a, "set_b": set_b}
    body = {
        "model": model,
        "messages": [
            {"role": "system", "content": SYSTEM_INSTRUCTION},
            {"role": "user", "content": json.dumps(payload, ensure_ascii=False)},
        ],
        "max_tokens": 16_000,
        "response_format": {"type": "json_object"},
    }

    try:
        response = requests.post(url, headers=headers, json=body, timeout=_DEEPSEEK_TIMEOUT_SECONDS)
        response.raise_for_status()
    except requests.Timeout as e:
        raise JudgeError(f"timeout ao chamar deepseek (limite: {_DEEPSEEK_TIMEOUT_SECONDS}s): {e}") from e
    except requests.RequestException as e:
        if e.response is not None and e.response.status_code == 402:
            raise JudgeBalanceExhausted("deepseek: saldo insuficiente (HTTP 402)") from e
        detail = f" -- corpo da resposta: {e.response.text[:2000]}" if e.response is not None else ""
        raise JudgeError(f"erro HTTP ao chamar deepseek: {e}{detail}") from e

    result = response.json()
    if "error" in result:
        error_info = result.get("error", {})
        raise JudgeError(f"erro da API deepseek: {error_info.get('message', error_info)}")

    choices = result.get("choices", [])
    finish_reason = choices[0].get("finish_reason") if choices else None
    message_content = choices[0].get("message", {}).get("content") if choices else None
    if not message_content:
        raise JudgeError(f"resposta de deepseek não contém conteúdo (finish_reason={finish_reason!r})")

    try:
        parsed = json.loads(message_content)
    except json.JSONDecodeError as e:
        raise JudgeError(f"resposta de deepseek não é JSON válido: {e} -- início: {message_content[:500]}") from e

    categories_raw = parsed.get("categories") if isinstance(parsed, dict) else parsed
    if not isinstance(categories_raw, list):
        raise JudgeError(f"resposta de deepseek não tem a chave 'categories' esperada: {str(parsed)[:500]}")
    return [Category.model_validate(c) for c in categories_raw]


def main() -> None:
    parser = argparse.ArgumentParser(description="Reconcilia duas listas de categorias (Etapa 2) numa só, via DeepSeek.")
    parser.add_argument("--v1", type=Path, default=None, help="Primeira lista de categorias (default: data/analysis/consenso_categorias.json).")
    parser.add_argument("--v2", type=Path, default=None, help="Segunda lista de categorias (default: data/analysis/consenso_categorias_v2.json).")
    parser.add_argument("--output", type=Path, default=None, help="JSON de saída (default: data/analysis/consenso_categorias_reconciliadas.json).")
    parser.add_argument("--model", type=str, default=DEFAULT_MODEL, help=f"model_id da DeepSeek (default: {DEFAULT_MODEL}).")
    args = parser.parse_args()

    v1_path = args.v1 or (DATA_DIR / "analysis" / "consenso_categorias.json")
    v2_path = args.v2 or (DATA_DIR / "analysis" / "consenso_categorias_v2.json")
    output_path = args.output or (DATA_DIR / "analysis" / "consenso_categorias_reconciliadas.json")

    for p in (v1_path, v2_path):
        if not p.exists():
            logger.error("%s não encontrado.", p)
            sys.exit(1)

    set_a = json.loads(v1_path.read_text(encoding="utf-8"))
    set_b = json.loads(v2_path.read_text(encoding="utf-8"))
    logger.info("Reconciliando %s categorias de %s com %s categorias de %s", len(set_a), v1_path.name, len(set_b), v2_path.name)

    api_key = os.environ.get("DEEPSEEK_API_KEY", "").strip()
    if not api_key:
        logger.error("DEEPSEEK_API_KEY não definida (ou vazia) no ambiente/.env. Veja .env.example.")
        sys.exit(1)

    try:
        categories = _call_deepseek_reconcile(set_a, set_b, args.model, api_key)
    except JudgeRefusal as e:
        logger.error("Recusado pelo provedor (categoria=%s).", e.category)
        sys.exit(1)
    except JudgeBalanceExhausted as e:
        logger.error("%s", e)
        sys.exit(1)
    except JudgeError as e:
        logger.error("Chamada à deepseek falhou: %s", e)
        sys.exit(1)

    logger.info("%s categorias reconciliadas:", len(categories))
    for c in categories:
        logger.info("  - %s", c.category)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps([c.model_dump() for c in categories], ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    logger.info("Categorias reconciliadas salvas em %s", output_path)


if __name__ == "__main__":
    try:
        main()
    except Exception:
        logger.exception("Reconciliação de categorias falhou")
        sys.exit(1)
